name: sqlfluff lint
on: [pull_request]
jobs:
  test-pr-review-lint:
    name: runner / sqlfluff-lint (github-pr-review)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write 
    env:
      ACCOUNT: ${{ secrets.SF_ACCOUNT }}
      USERNAME: ${{ secrets.SF_USER }}
      PASSWORD: ${{ secrets.SF_PASSWORD }}
      DATABASE: ${{ secrets.SF_DATABASE }}
      SCHEMA: ${{ secrets.SF_SCHEMA }}
      WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
    steps:
      - uses: actions/checkout@v4
      - uses: tetracionist/action-reviewdog-sqlfluff@v0.2.0
        with:
          github_token: ${{ secrets.github_token }}
          dbt_project_dir: ./testdata/dbt
          level: error 
          reporter: github-pr-review
          sqlfluff_mode: lint


# name: sqlfluff_fix
# on: [pull_request]
# jobs:
#   test-pr-review-fix:
#     name: runner / sqlfluff-fix (github-pr-review)
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       pull-requests: write 
#     env:
#       ACCOUNT: ${{ secrets.ACCOUNT }}
#       USERNAME: ${{ secrets.USER }}
#       PASSWORD: ${{ secrets.PASSWORD }}
#       DATABASE: ${{ secrets.DATABASE }}
#       SCHEMA: ${{ secrets.SCHEMA }}
#       WAREHOUSE: ${{ secrets.WAREHOUSE }}
    
#     steps:
#       - uses: actions/checkout@v4
#       - uses: tetracionist/action-reviewdog-sqlfluff@v0.2.0
#         with:
#           github_token: ${{ secrets.github_token }}
#           dbt_project_dir: ./testdata/dbt
#           level: error 
#           reporter: github-pr-review
#           sqlfluff_mode: fix
